import turtle 

greg = turtle.Turtle()

class graphics:
  def __init__(self):
    self.greg = turtle.Turtle()
  def drawcampuscenter(self, greg):
    self.greg.clear()
    self.greg.reset()
    self.greg.pendown()
    self.greg.left(90)
    self.greg.forward(100)
    self.greg.left(50)
    self.greg.forward(10)
    self.greg.right(90)
    self.greg.forward(6)
    self.greg.right(90)
    self.greg.forward(80)
    self.greg.right(90)
    self.greg.forward(6)
    self.greg.right(90)
    self.greg.forward(80)
    self.greg.penup()

    self.greg.left(130)
    self.greg.forward(108)
    self.greg.left(90)
    self.greg.forward(6)
    self.greg.pendown()
    self.greg.forward(200)
    self.greg.left(90)
    self.greg.forward(100)
    self.greg.left(100)
    self.greg.forward(100)
    self.greg.left(90)
    self.greg.forward(8)
    self.greg.left(90)
    self.greg.forward(10)
    self.greg.left(110)
    self.greg.forward(5)
    self.greg.right(110)
    self.greg.forward(90)
    self.greg.penup()
    self.greg.left(80)
    self.greg.forward(6)
    self.greg.left(100)
    self.greg.forward(100)
    self.greg.right(90)
    self.greg.left(95)
    self.greg.pendown()
    self.greg.forward(55)
    self.greg.penup()
    self.greg.forward(100)
    self.greg.left(90)
    self.greg.forward(80)
    self.greg.write("Checkpoint",font=("Verdana",15))
  def drawparkhouse(self, greg):
    self.greg.clear()
    self.greg.reset()
    self.greg.penup()
    self.greg.right(180)
    self.greg.forward(200)
    self.greg.left(90)
    self.greg.forward(50)

    self.greg.pendown()
    self.greg.left(180)
    self.greg.forward(100)
    self.greg.right(50)
    self.greg.forward(90)
    self.greg.right(80)
    self.greg.forward(90)
    self.greg.right(140)
    self.greg.forward(140)

    self.greg.penup()
    self.greg.left(90)
    self.greg.forward(100)
    self.greg.left(90)
    self.greg.forward(50)
    self.greg.left(90)

    self.greg.pendown()
    self.greg.forward(45)
    self.greg.right(50)
    self.greg.forward(30)
    self.greg.right(80)
    self.greg.forward(30)
    self.greg.right(140)
    self.greg.forward(46.667)

    self.greg.penup()
    self.greg.right(180)
    self.greg.forward(46.667)

    self.greg.pendown()
    self.greg.right(90)
    self.greg.forward(45)

    self.greg.penup()
    self.greg.right(90)
    self.greg.forward(91.667)
    self.greg.left(180)

    self.greg.pendown()
    self.greg.forward(135)
    self.greg.left(90)
    self.greg.forward(100)
    self.greg.right(80)
    self.greg.forward(140)
    self.greg.left(130)
    self.greg.forward(60)
    self.greg.left(100)
    self.greg.forward(60)

    self.greg.penup()
    self.greg.right(180)
    self.greg.forward(60)
 
    self.greg.pendown()
    self.greg.left(130)
    self.greg.forward(140)
    self.greg.left(80)

    self.greg.penup()
    self.greg.forward(145)
    self.greg.left(100)
    self.greg.forward(43)

    self.greg.pendown()
    self.greg.forward(155)
    self.greg.left(85)
    self.greg.forward(98)
  
    self.greg.write("Checkpoint",font=("Verdana",15))

